-- 코드를 입력하세요
WITH BOOK_AUTHOR AS (
    SELECT B.AUTHOR_ID, PRICE, CATEGORY, AUTHOR_NAME, BOOK_ID
    FROM BOOK B
    JOIN AUTHOR A
    ON B.AUTHOR_ID = A.AUTHOR_ID
)

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK_AUTHOR A
JOIN BOOK_SALES S
ON A.BOOK_ID = S.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;