-- 코드를 작성해주세요
WITH SECOND AS (
SELECT C.*
FROM ECOLI_DATA AS P
JOIN ECOLI_DATA AS C
ON C.PARENT_ID = P.ID
WHERE P.PARENT_ID IS NULL
)

SELECT C.ID
FROM SECOND
JOIN ECOLI_DATA AS C
ON C.PARENT_ID = SECOND.ID
ORDER BY ID;
