-- 코드를 입력하세요
# WITH RECURSIVE CTE AS
# (
#   SELECT 0 AS N
#   UNION ALL
#   SELECT N + 1 FROM CTE WHERE N < 23
# )

# SELECT N AS HOUR, COUNT(ANIMAL_ID) AS COUNT
# FROM ANIMAL_OUTS 
#     RIGHT JOIN CTE
#     ON CTE.N = ANIMAL_OUTS.HOUR(DATETIME)
# GROUP BY N
# ORDER BY N;
-- 
WITH RECURSIVE cte AS
(
  SELECT 0 AS n
  UNION ALL
  SELECT n + 1 FROM cte WHERE n < 23
)
SELECT n AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM cte LEFT JOIN ANIMAL_OUTS ON n = HOUR(DATETIME)
GROUP BY HOUR
ORDER BY HOUR