-- 코드를 작성해주세요
SELECT I.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO AS I NATURAL JOIN ITEM_TREE AS T
WHERE PARENT_ITEM_ID IN(SELECT ITEM_ID
                        FROM ITEM_INFO
                        WHERE RARITY = 'RARE')
ORDER BY I.ITEM_ID DESC;