-- 코드를 작성해주세요
SELECT CHILD.ID, CHILD.GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS CHILD
LEFT JOIN ECOLI_DATA AS PARENT
ON CHILD.PARENT_ID = PARENT.ID
WHERE PARENT.GENOTYPE & CHILD.GENOTYPE = PARENT.GENOTYPE
ORDER BY ID;