-- 코드를 작성해주세요
WITH MAXS AS (
    SELECT DISTINCT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        MAX(SIZE_OF_COLONY) OVER(PARTITION BY YEAR(DIFFERENTIATION_DATE)) AS MAXSIZE
    FROM ECOLI_DATA
)

SELECT 
    M.YEAR,
    (M.MAXSIZE - E.SIZE_OF_COLONY) YEAR_DEV,
    E.ID
FROM MAXS M 
JOIN ECOLI_DATA E
ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY M.YEAR, YEAR_DEV;
