-- 코드를 입력하세요
# SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE PRICE IN (
#     SELECT MAX(PRICE)
#     FROM FOOD_PRODUCT
#     GROUP BY CATEGORY
# ) AND CATEGORY IN ('과자','국','김치','식용유')
# GROUP BY CATEGORY
# ORDER BY PRICE DESC;


SELECT A.CATEGORY, A.MAX_PRICE, A.PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE,
        MAX(PRICE) OVER (PARTITION BY CATEGORY) MAX_PRICE, PRODUCT_NAME
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')) A
WHERE A.MAX_PRICE = A.PRICE
ORDER BY 2 DESC;